// PrintablePlan.jsx
// A beautifully styled, print-ready version of the surprise plan.
// Hidden from normal view — only rendered when printing.

import { forwardRef } from "react";

const PrintablePlan = forwardRef(function PrintablePlan({ result, form }, ref) {
  if (!result) return null;

  const phases = [
    { label: "Before the day", color: "#534AB7", items: result.timeline?.before || [] },
    { label: "On the day",     color: "#1D9E75", items: result.timeline?.during || [] },
    { label: "After",          color: "#BA7517", items: result.timeline?.after  || [] },
  ];

  return (
    <div ref={ref} style={{
      fontFamily: "'Georgia', serif",
      padding: "40px 48px",
      maxWidth: "680px",
      margin: "0 auto",
      color: "#111",
      lineHeight: "1.7",
    }}>
      {/* Header */}
      <div style={{ borderBottom: "2px solid #534AB7", paddingBottom: "16px", marginBottom: "28px" }}>
        <div style={{ fontSize: "11px", fontWeight: "700", letterSpacing: "0.15em", textTransform: "uppercase", color: "#534AB7", marginBottom: "6px" }}>
          AI Surprise Planner
        </div>
        <h1 style={{ fontSize: "26px", fontWeight: "700", margin: "0 0 6px", lineHeight: "1.3" }}>
          {result.idea}
        </h1>
        <div style={{ fontSize: "13px", color: "#666" }}>
          {form.tone} · {form.occasion} · {form.relationship} · Rs {Number(form.budget).toLocaleString("en-IN")}
          {form.city ? ` · ${form.city}` : ""}
        </div>
      </div>

      {/* Personal message */}
      <div style={{ background: "#F7F6FF", borderLeft: "3px solid #534AB7", padding: "14px 18px", borderRadius: "0 8px 8px 0", marginBottom: "28px" }}>
        <div style={{ fontSize: "11px", fontWeight: "700", textTransform: "uppercase", letterSpacing: "0.1em", color: "#534AB7", marginBottom: "6px" }}>Personal Message</div>
        <p style={{ margin: 0, fontStyle: "italic", fontSize: "14px", color: "#333" }}>"{result.message}"</p>
      </div>

      {/* Why this plan */}
      <div style={{ marginBottom: "28px" }}>
        <div style={{ fontSize: "11px", fontWeight: "700", textTransform: "uppercase", letterSpacing: "0.1em", color: "#888", marginBottom: "8px" }}>Why this plan</div>
        <p style={{ margin: 0, fontSize: "13px", color: "#444" }}>{result.explanation}</p>
      </div>

      {/* Timeline */}
      <div style={{ marginBottom: "28px" }}>
        <div style={{ fontSize: "11px", fontWeight: "700", textTransform: "uppercase", letterSpacing: "0.1em", color: "#888", marginBottom: "14px" }}>Your Timeline</div>
        {phases.map(ph => (
          <div key={ph.label} style={{ marginBottom: "16px" }}>
            <div style={{ fontSize: "12px", fontWeight: "700", color: ph.color, marginBottom: "8px", textTransform: "uppercase", letterSpacing: "0.08em" }}>{ph.label}</div>
            {ph.items.map((item, i) => (
              <div key={i} style={{ display: "flex", alignItems: "flex-start", gap: "10px", marginBottom: "6px", fontSize: "13px" }}>
                <div style={{ width: "16px", height: "16px", borderRadius: "3px", border: `1.5px solid ${ph.color}`, flexShrink: 0, marginTop: "2px" }} />
                <span>{item.replace(/^[-•]\s*/, "")}</span>
              </div>
            ))}
          </div>
        ))}
      </div>

      {/* Budget breakdown */}
      {result.budget_breakdown && (
        <div style={{ marginBottom: "28px" }}>
          <div style={{ fontSize: "11px", fontWeight: "700", textTransform: "uppercase", letterSpacing: "0.1em", color: "#888", marginBottom: "12px" }}>Budget Breakdown</div>
          {Object.entries(result.budget_breakdown).map(([k, v]) => (
            <div key={k} style={{ display: "flex", justifyContent: "space-between", borderBottom: "0.5px solid #eee", padding: "7px 0", fontSize: "13px" }}>
              <span>{k}</span>
              <span style={{ fontWeight: "600" }}>Rs {Number(v).toLocaleString("en-IN")}</span>
            </div>
          ))}
          <div style={{ display: "flex", justifyContent: "space-between", padding: "8px 0 0", fontSize: "14px", fontWeight: "700", color: "#534AB7" }}>
            <span>Total</span>
            <span>Rs {Number(form.budget).toLocaleString("en-IN")}</span>
          </div>
        </div>
      )}

      {/* Footer */}
      <div style={{ borderTop: "1px solid #eee", paddingTop: "14px", fontSize: "11px", color: "#bbb", textAlign: "center" }}>
        Generated by AI Surprise Planner · surprise-planner-nu.vercel.app
      </div>
    </div>
  );
});

export default PrintablePlan;
