// TermsOfService.jsx — Legal page
export default function TermsOfService({ onBack }) {
  return (
    <div style={{ width: "100%", minHeight: "100vh", overflowX: "hidden", background: "#080808", color: "#fff", fontFamily: "'DM Sans', sans-serif" }}>
      <nav style={{ position: "sticky", top: 0, zIndex: 90, display: "flex", alignItems: "center", justifyContent: "space-between", padding: "20px clamp(24px, 5vw, 80px)", background: "rgba(8,8,8,0.92)", backdropFilter: "blur(24px)", borderBottom: "1px solid rgba(255,255,255,0.05)" }}>
        <div onClick={onBack} style={{ letterSpacing: "0.18em", color: "#D4AF37", cursor: "pointer", textTransform: "uppercase", fontFamily: "'Cormorant Garamond', serif", fontSize: "18px" }}>
          ✦ AI Surprise Planner
        </div>
        <button onClick={onBack} style={{ padding: "8px 20px", background: "none", border: "1px solid rgba(255,255,255,0.15)", color: "rgba(255,255,255,0.5)", fontSize: "12px", cursor: "pointer", fontFamily: "inherit", borderRadius: "6px" }}>← Back</button>
      </nav>

      <div style={{ maxWidth: "720px", margin: "0 auto", padding: "60px 24px 100px", boxSizing: "border-box" }}>
        <div style={{ fontSize: "10px", letterSpacing: "0.3em", color: "#D4AF37", textTransform: "uppercase", marginBottom: "16px", opacity: 0.7 }}>Legal</div>
        <h1 style={{ fontFamily: "'Cormorant Garamond', serif", fontSize: "clamp(36px, 5vw, 52px)", fontWeight: "300", marginBottom: "16px" }}>
          Terms of <span style={{ color: "#D4AF37", fontStyle: "italic" }}>Service</span>
        </h1>
        <p style={{ fontSize: "13px", color: "rgba(255,255,255,0.3)", marginBottom: "48px" }}>Last updated: April 2026</p>

        {[
          { title: "1. Acceptance of Terms", body: "By accessing or using AI Surprise Planner, you agree to be bound by these Terms of Service. If you do not agree, please do not use the service." },
          { title: "2. Service Description", body: "AI Surprise Planner is an AI-powered platform that generates personalised surprise plans. The service includes plan generation, vendor matching, plan sharing, and premium features. We reserve the right to modify or discontinue features at any time." },
          { title: "3. User Accounts", body: "You may create an account using your email address. You are responsible for maintaining the security of your account. You must provide accurate information and notify us of any unauthorized access." },
          { title: "4. AI-Generated Content", body: "Plans, messages, and suggestions are generated by artificial intelligence. While we strive for quality and relevance:\n\n• AI outputs may not always be accurate or suitable\n• Plans are suggestions only — execution is your responsibility\n• We are not liable for any outcomes resulting from following AI-generated plans\n• Budget breakdowns are estimates and may vary in practice" },
          { title: "5. Vendor Listings", body: "Vendors who list their business on our platform:\n\n• Must provide accurate business information\n• Are responsible for the quality of their services\n• May have their listing reviewed and approved/rejected by our team\n• Can update or remove their listing at any time\n\nAI Surprise Planner does not guarantee the quality of vendor services and acts only as a matching platform." },
          { title: "6. Pro Subscription", body: "The Pro tier is billed via Razorpay at Rs 299/month. Subscriptions auto-renew unless cancelled. Features include PDF export, unlimited saves, and priority features. No refunds for partial months. Cancel anytime from your account settings." },
          { title: "7. Acceptable Use", body: "You agree not to:\n\n• Use the service for illegal or harmful purposes\n• Submit false or misleading information\n• Attempt to reverse-engineer or hack the platform\n• Spam vendors with irrelevant quote requests\n• Scrape or harvest data from the platform" },
          { title: "8. Intellectual Property", body: "AI Surprise Planner owns all platform IP including design, code, and branding. AI-generated plans are provided for your personal use. You may share plans via our built-in sharing features." },
          { title: "9. Limitation of Liability", body: "AI Surprise Planner is provided \"as is\" without warranties. We are not liable for:\n\n• Damages from using AI-generated plans\n• Vendor service quality\n• Payment processing issues handled by Razorpay\n• Data loss or service interruptions\n\nOur total liability is limited to the amount you paid us in the last 12 months." },
          { title: "10. Contact", body: "For questions about these terms:\n\nEmail: bhaveshkumawat330@gmail.com\nAI Surprise Planner, India" },
        ].map((section) => (
          <div key={section.title} style={{ marginBottom: "40px" }}>
            <h2 style={{ fontSize: "18px", fontWeight: "600", color: "rgba(255,255,255,0.85)", marginBottom: "16px", letterSpacing: "0.01em" }}>{section.title}</h2>
            <p style={{ fontSize: "14px", color: "rgba(255,255,255,0.45)", lineHeight: "1.9", whiteSpace: "pre-line" }}>{section.body}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
